version: '3'

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - 5001:5001
      - 8080:8080
    volumes:
      - './configs/ipfs.config:/data/ipfs/config'

  ganache:
    image: trufflesuite/ganache
    ports:
      - 8545:8545
    command: --wallet.deterministic
