version: '3'

services:
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 5001:5001
      - 8080:8080
    volumes:
      - './ipfs.sh:/ipfs.sh'
    entrypoint: 'sh ipfs.sh'

  caddy:
    image: caddy
    ports:
      - 80:80
    volumes:
      - './caddy.conf:/srv/Caddyfile'
    environment:
      PORT: 81
    command: caddy run --config Caddyfile
