name: pages

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: current
          cache-dependency-path: app/package-lock.json
      - run: npm ci
      - run: npm run build

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: npm ci
      - run: npm run build

      - uses: JamesIves/github-pages-deploy-action@4.0.0
        if: github.ref == 'refs/heads/master'
        with:
          branch: gh-pages
          folder: ./dist
          single-commit: true
          silent: false
